/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.scene {
    export class gameSceneUI extends Laya.Scene {
		public background:Laya.Sprite;
		public scaleGroup:Laya.Box;
		public gameBox:Laya.Sprite;
		public buff:Laya.Box;
		public item:Laya.Box;
		public btnBomb:Laya.Button;
		public bomb:Laya.Label;
		public score:Laya.Label;
		public resultScore:Laya.Box;
		public curScore:Laya.Label;
		public maxScore:Laya.Label;
		public result:Laya.Box;
		public tips:Laya.Label;
		public btnContinue:Laya.Button;
		public btnRestart:Laya.Button;
		public btnBack:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scene/gameScene");
        }
    }
    REG("ui.scene.gameSceneUI",gameSceneUI);
    export class loginSceneUI extends Laya.Scene {
		public background:Laya.Sprite;
		public scaleGroup:Laya.Box;
		public menu:Laya.Box;
		public btnStart:Laya.Button;
		public btnRank:Laya.Button;
		public btnSetting:Laya.Button;
		public setting:Laya.Box;
		public btnMusic:Laya.Button;
		public btnSound:Laya.Button;
		public btnBack:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scene/loginScene");
        }
    }
    REG("ui.scene.loginSceneUI",loginSceneUI);
}