/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameScene from "./view/game/GameScene"
import Background from "./view/game/Background"
import GameControl from "./view/game/GameControl"
import LoginScene from "./view/login/LoginScene"
import Hero from "./view/game/Hero"
import Buff from "./view/game/Buff"
import Bullet from "./view/game/Bullet"
import Enemy from "./view/game/Enemy"
import Ufo from "./view/game/Ufo"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=960;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="scene/loginScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("view/game/GameScene.ts",GameScene);
        reg("view/game/Background.ts",Background);
        reg("view/game/GameControl.ts",GameControl);
        reg("view/login/LoginScene.ts",LoginScene);
        reg("view/game/Hero.ts",Hero);
        reg("view/game/Buff.ts",Buff);
        reg("view/game/Bullet.ts",Bullet);
        reg("view/game/Enemy.ts",Enemy);
        reg("view/game/Ufo.ts",Ufo);
    }
}
GameConfig.init();